In [9]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
# One hot representation
one_hot_rep = [one_hot(words, voc_size)for words in sent]
one_hot_rep

[[7698, 1138, 6058, 9253],
 [7698, 1138, 6058, 5867],
 [7698, 9434, 6058, 4324],
 [6894, 1705, 7439, 5777, 3566],
 [6894, 1705, 7439, 5777, 4131],
 [3956, 7698, 8804, 6058, 4546],
 [4667, 7629, 6201, 5777]]

In [8]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
sentence_length = 8
embedded_docs = pad_sequences(one_hot_rep,padding='pre',maxlen=sentence_length)
print(embedded_docs)

[[   0    0    0    0 7698 1138 6058 9253]
 [   0    0    0    0 7698 1138 6058 5867]
 [   0    0    0    0 7698 9434 6058 4324]
 [   0    0    0 6894 1705 7439 5777 3566]
 [   0    0    0 6894 1705 7439 5777 4131]
 [   0    0    0 3956 7698 8804 6058 4546]
 [   0    0    0    0 4667 7629 6201 5777]]


In [11]:
# Feature representation
dim=10

In [15]:
model = Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step


array([[[-0.04751364,  0.03684846, -0.00575062,  0.04955677,
         -0.04056656, -0.00303103,  0.01848331, -0.01811018,
          0.03577626, -0.03545628],
        [-0.04751364,  0.03684846, -0.00575062,  0.04955677,
         -0.04056656, -0.00303103,  0.01848331, -0.01811018,
          0.03577626, -0.03545628],
        [-0.04751364,  0.03684846, -0.00575062,  0.04955677,
         -0.04056656, -0.00303103,  0.01848331, -0.01811018,
          0.03577626, -0.03545628],
        [-0.04751364,  0.03684846, -0.00575062,  0.04955677,
         -0.04056656, -0.00303103,  0.01848331, -0.01811018,
          0.03577626, -0.03545628],
        [ 0.02002299, -0.00713808, -0.01546121,  0.00379869,
         -0.02750148,  0.0446997 ,  0.02833506,  0.04879021,
         -0.00734561,  0.04101485],
        [ 0.03395009, -0.04554332, -0.03311061,  0.04326571,
          0.01524113,  0.03323111, -0.00130118, -0.03983523,
          0.01980431,  0.0236466 ],
        [ 0.02771982, -0.02917352, -0.04869839, -0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 7698, 1138, 6058, 9253], dtype=int32)